### ISSUE TITLE
Not able to convert to png buffer due to few errors

### ISSUE THREAD

**Issue by anonymousCoders3** [dichovsky/pdf-to-png-converter#76]
Hi. Why I been getting this error? Can someone please help. Thanks

node v20.9.0

Warning: Cannot access the `require` function: "TypeError: process.getBuiltinModule is not a function".
Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
Warning: Cannot polyfill `ImageData`, rendering may be broken.
Warning: Cannot polyfill `Path2D`, rendering may be broken.

**Comment by dichovsky** [comment]
@anonymousCoders3 @Pitsbeary Please share more details / steps for reproduce including OS architecture, environment, PDF file, converter configuartion

**Comment by dimaip** [comment]
I have the same issue.
Installed with `yarn add pdf-to-png-converter --ignore-engines` (why block yarn btw?)
```
 "pdf-to-png-converter": "^3.6.4",
```
Macos 14.6.1.
node 20.9.

With node 22 it works, but I can't use it yet.

**Comment by dimaip** [comment]
`getBuiltInModule` is only available since 20.16: https://nodejs.org/en/blog/release/v20.16.0
I think we can use that version. Would make sense to add to `engines`.

**Comment by anonymousCoders3** [comment]
new update! 

its working now with below setup

node: 22.14.0
"pdf-to-png-converter": "3.6.4"

**Comment by sb3455261** [comment]
doesn't work with 21.7, nor with 20.14, nor with 22.14, even with worker, even as it is
smth like
webpack://pdf.js/src/display/api.js:3119
        throw new Error(
              ^


Error: startCleanup: Page 4 is currently rendering.
    at WorkerTransport.startCleanup (webpack://pdf.js/src/display/api.js:3119:15)

have seen all those warnings from the op as well.
