### ISSUE TITLE
TypeError: process.getBuiltinModule is not a function

### ISSUE THREAD

**Issue by NotVenuMadhav** [dichovsky/pdf-to-png-converter#69]
installed the latest version, and this error pops.

TypeError: process.getBuiltinModule is not a function
    at NodeCanvasFactory._createCanvas (endpoints/node_modules/pdf-to-png-converter/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10899:29)
    at NodeCanvasFactory.create (endpoints/node_modules/pdf-to-png-converter/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10372:25)
    at processPdfPage (endpoints\node_modules\pdf-to-png-converter\out\pdfToPng.js:80:59)
    at async Promise.all (index 0)
    at async pdfToPng (endpoints\node_modules\pdf-to-png-converter\out\pdfToPng.js:36:32)

**Comment by dichovsky** [comment]
> installed the latest version, and this error pops.
> 
> TypeError: process.getBuiltinModule is not a function at NodeCanvasFactory._createCanvas (endpoints/node_modules/pdf-to-png-converter/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10899:29) at NodeCanvasFactory.create (endpoints/node_modules/pdf-to-png-converter/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10372:25) at processPdfPage (endpoints\node_modules\pdf-to-png-converter\out\pdfToPng.js:80:59) at async Promise.all (index 0) at async pdfToPng (endpoints\node_modules\pdf-to-png-converter\out\pdfToPng.js:36:32)

@NotVenuMadhav please provide clear steps for reproduce

**Comment by jonaswoehl** [comment]
+1 from my side.

Node Version: 22.12.0
The error occurs since I updated pdf-to-png-converter from 2.3.0 to 3.5.2

**Comment by yedidmh** [comment]
We're having the same issue. 

On Debian, tried a number of versions of this package, all of them with the same issue.

We also tried installing it both via yarn and npm, no difference.

**Comment by dichovsky** [comment]
v3.6.3 works on macOS 15.2 (arm), Windows 11 and node:20-bullseye, node:20-bookworm, node:22-bullseye, node:22-bookworm docker images with no issues.

@yedidmh @jonaswoehl 
guys, I cannot help without clear steps for reproduce

**Comment by jonaswoehl** [comment]
@yedidmh thanks for the hint, for me installing the latest @tomatrow/pdf-to-png-converter (version 3.5.2) works, too. Afterwards I tried to install version 3.5.2 of the original package, but this throws the same error mentioned above for me.

@dichovsky to clarify: i'm using the ubuntu:latest docker image with the current node lts version and the error occurs with multiple pdf inputs, so the source file does not seem to be the issue. please let us know, which further details you need to reproduce the error.

**Comment by dichovsky** [comment]
@NotVenuMadhav @jonaswoehl @EHadoux @yedidmh 
Please try 3.6.4

**Comment by yigitsimsek** [comment]
I also have the same problem with version 3.6.4.

Node.js version: 18.x (Alpine-based Docker image)
Library version: pdfToPng 3.6.4
Dependency: pdfjs-dist (used internally by pdfToPng)
Operating system: Alpine Linux (via Docker)
Environment: Docker container

**Comment by glodfinch** [comment]
This occurred for me on Node v18, I just updated to v22 lts and it was resolved.

**Comment by AhmadMuj** [comment]
I can confirm that this issue has been resolved when I upgraded my node from v20 to v22

I'm on version "pdf-to-png-converter": "^3.6.4"

**Comment by Pitsbeary** [comment]
What if someone cannot use Node v22 and needs to stick with v20?
3.6.4 not working and produces same error as mentioned in Issue title.
